// Copyright 2026 secret_com Authors. All rights reserved.
// Use of this source code is governed by an Apache-2.0 license.

// client_demo.cc — Example: authorization client running on the user device.
//
// Build: cmake --build . --target client_demo
// Run:   ./client_demo /dev/ttyUSB0 115200

#include <cstdio>
#include <cstring>
#include <memory>

#include "secret_com/auth_client.h"
#include "secret_com/types.h"
#include "src/transport/serial_transport.h"

// ---------------------------------------------------------------------------
// ESC device static public key — embedded at build time.
// In production this should be baked in via a code-signed header or a
// provisioning step; NEVER ship the private key in client code.
// ---------------------------------------------------------------------------
static const uint8_t kEscDevicePublicKey[secret_com::kEcPublicKeySize] = {
  // Replace with the actual 65-byte uncompressed P-256 public key
  // generated by the keygen tool (see docs/INTEGRATION_GUIDE.md).
  0x04,  // Uncompressed point marker
  // X coordinate (32 bytes) — placeholder zeros:
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  // Y coordinate (32 bytes) — placeholder zeros:
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

int main(int argc, char* argv[]) {
  if (argc < 3) {
    fprintf(stderr, "Usage: %s <serial_port> <baud_rate>\n", argv[0]);
    fprintf(stderr, "  e.g. %s /dev/ttyUSB0 115200\n", argv[0]);
    return 1;
  }

  const char*    port  = argv[1];
  const uint32_t baud  = static_cast<uint32_t>(atoi(argv[2]));

  // 1. Create serial transport.
  auto transport = std::make_unique<secret_com::SerialTransport>(port, baud);

  // 2. Configure crypto with the ESC's embedded public key.
  secret_com::CryptoConfig crypto_cfg;
  memcpy(crypto_cfg.device_public_key, kEscDevicePublicKey,
         secret_com::kEcPublicKeySize);
  crypto_cfg.is_server = false;

  // 3. Initialize client.
  secret_com::AuthClient client;
  secret_com::Status s = client.Initialize(std::move(transport), crypto_cfg);
  if (s != secret_com::Status::kOk) {
    fprintf(stderr, "Initialize failed: %s\n", secret_com::StatusToString(s));
    return 1;
  }

  // 4. Build auth request.
  secret_com::AuthRequest req;
  req.client_device_id = 0xDEADBEEF;  // Replace with real device ID.
  strncpy(req.product_name, "ESC-Pro-X1", sizeof(req.product_name));
  req.feature_flags = secret_com::kFeatureAll;

  // 5. Request authorization (async; blocks this thread via condition var).
  bool          done   = false;
  bool          result = false;
  std::mutex    mtx;
  std::condition_variable cv;

  s = client.RequestAuthorization(
      req,
      [&](secret_com::Status status, const secret_com::LicenseInfo& lic) {
        {
          std::lock_guard<std::mutex> lk(mtx);
          if (status == secret_com::Status::kOk) {
            printf("✓ Authorization granted!\n");
            printf("  Product   : %s\n", lic.product_name);
            printf("  Device ID : 0x%08X\n", lic.device_id);
            printf("  Type      : %d\n", static_cast<int>(lic.type));
            printf("  Features  : 0x%02X\n", lic.feature_flags);
            printf("  Issued    : %llu\n",
                   static_cast<unsigned long long>(lic.issue_timestamp));
            result = true;
          } else {
            printf("✗ Authorization failed: %s\n",
                   secret_com::StatusToString(status));
            result = false;
          }
          done = true;
        }
        cv.notify_one();
      },
      10000 /* 10 s timeout */);

  if (s != secret_com::Status::kOk) {
    fprintf(stderr, "RequestAuthorization failed immediately: %s\n",
            secret_com::StatusToString(s));
    return 1;
  }

  // Wait for callback.
  {
    std::unique_lock<std::mutex> lk(mtx);
    cv.wait(lk, [&]{ return done; });
  }

  client.Shutdown();
  return result ? 0 : 1;
}
